force-app/main/default/objects/Account/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>Date Of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ADF_Status__c.field-meta.xml
<CustomField>
    <fullName>ADF_Status__c</fullName>
    <defaultValue>"Draft"</defaultValue>
    <label>ADF Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>FirstName</description>
    <inlineHelpText>FirstName</inlineHelpText>
    <label>FirstName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/GroupBatchNumber__c.field-meta.xml
<CustomField>
    <fullName>GroupBatchNumber__c</fullName>
    <label>Group Batch Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>LastName</description>
    <inlineHelpText>LastName</inlineHelpText>
    <label>Last Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>linkes the patient ID and not a name to the treatment case</description>
    <inlineHelpText>type "ID" for lookup search</inlineHelpText>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PRF_Status__c.field-meta.xml
<CustomField>
    <fullName>PRF_Status__c</fullName>
    <defaultValue>"Draft"</defaultValue>
    <label>PRF Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PRFApprovedDate__c.field-meta.xml
<CustomField>
    <fullName>PRFApprovedDate__c</fullName>
    <inlineHelpText>Product Request Approved Date/Time</inlineHelpText>
    <label>Product Request Approved Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/PRFSubmittedDate__c.field-meta.xml
<CustomField>
    <fullName>PRFSubmittedDate__c</fullName>
    <inlineHelpText>Product Request Submitted Date/Time</inlineHelpText>
    <label>Product Request Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purpose</label>
    <referenceTo>Purpose__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Status_Finished_Product_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Status_Finished_Product_Delivery__c</fullName>
    <label>Status - Finished Product Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Finished Product Delivery - Waiting Confirmation</fullName>
                <default>true</default>
                <label>Finished Product Delivery - Waiting Confirmation</label>
            </value>
            <value>
                <fullName>Finished Product Delivery - Planned</fullName>
            </value>
            <value>
                <fullName>Finished Product - Released from Manufacturing Plant</fullName>
            </value>
            <value>
                <fullName>Finished Product - Released from Manufacturing Plant Reversed</fullName>
            </value>
            <value>
                <fullName>Finished Product - Shipped from Manufacturing Plant</fullName>
            </value>
            <value>
                <fullName>Finished Product - Shipped from Manufacturing Plant Reversed</fullName>
            </value>
            <value>
                <fullName>Finished Product - Received</fullName>
            </value>
            <value>
                <fullName>Finished Product Delivery - Cancelled</fullName>
            </value>
            <value>
                <fullName>Finished Product - Released by Novartis</fullName>
            </value>
            <value>
                <fullName>Finished Product - Released by Novartis Reversed</fullName>
            </value>
            <value>
                <fullName>Finished Product - Shipped to Treatment Center</fullName>
            </value>
            <value>
                <fullName>Finished Product - Shipped to Treatment Center Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Treatment.recordType-meta.xml
<RecordType>
    <fullName>Treatment</fullName>
    <active>true</active>
    <businessProcess>Treatment</businessProcess>
    <description>Used for the regular Treatments / holding the core PRF information</description>
    <label>Treatment</label>
</RecordType>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <description>Master record of the patient</description>
    <label>Patient</label>
    <nameField>
        <displayFormat>ID-SF-{000000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <description>Standard Date Field, will be split to 3 fields by formula</description>
    <inlineHelpText>Select the DOB of patient in Date Format</inlineHelpText>
    <label>Date of Birth (DOB)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First Name of Patient</description>
    <inlineHelpText>First Name of Patient</inlineHelpText>
    <label>First Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last Name of Patient</description>
    <inlineHelpText>Last Full Name of Patient</inlineHelpText>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/PatientAccount__c.field-meta.xml
<CustomField>
    <fullName>PatientAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Patient Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purpose__c/Purpose__c.object-meta.xml
<CustomObject>
    <label>Purpose</label>
    <nameField>
        <label>Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purposes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DashboardController.cls
public with sharing class DashboardController {
	@AuraEnabled
	public static List<Case> loadCases() {
		return [SELECT Priority, Purpose__r.Name, Purpose__r.Id, Id, Contact.Name, Subject, Status, CaseNumber, Patient__r.FirstName__c, Patient__r.LastName__c, Patient__r.DateOfBirth__c, GroupBatchNumber__c, PRF_Status__c, Status_Apheresis_Procedure__c, Status_Apheresis_Pickup__c, Status_Finished_Product_Delivery__c FROM Case WHERE RecordType.Name = 'Treatment' ORDER BY CaseNumber DESC];
	}

	@AuraEnabled
	public static Case updateCaseStatus(String caseId) {
		Case myCase = [SELECT Id, PRF_Status__c FROM Case WHERE Id =: caseId];
		myCase.PRF_Status__c = 'Submitted';
		update myCase;
		return myCase;
	}

	@AuraEnabled
	public static Case loadThisCase(String caseId) {
		return [SELECT Id, Patient__r.Name, Purpose__r.Name, Account.Name, Priority, Subject, PRF_Status__c, 	ADF_Status__c, PRFSubmittedDate__c, PRFApprovedDate__c FROM Case WHERE Id =: caseId];
	}
}